#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import csv
import os
from datetime import datetime

def extract_year_from_title(title):
    """Извлечь год из названия фильма в формате 'Title (Year)'"""
    if title and title[-1] == ')':
        try:
            return int(title[-5:-1])
        except ValueError:
            return None
    return None

def extract_title(title):
    """Извлечь название без года"""
    if title and title[-1] == ')' and len(title) > 6:
        return title[:-6].strip()
    return title

def read_movies(filename):
    """Прочитать информацию о фильмах из CSV"""
    movies = []
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                movie_id = row['movieId']
                title = extract_title(row['title'])
                year = extract_year_from_title(row['title'])
                genres = row['genres']
                movies.append((movie_id, title, year, genres))
    except Exception as e:
        print(f"Error reading {filename}: {e}")
    return movies

def read_ratings(filename):
    """Прочитать рейтинги из CSV"""
    ratings = []
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                rating_id = row['userId'] + '_' + row['movieId']
                user_id = row['userId']
                movie_id = row['movieId']
                rating = row['rating']
                timestamp = row['timestamp']
                ratings.append((rating_id, user_id, movie_id, rating, timestamp))
    except Exception as e:
        print(f"Error reading {filename}: {e}")
    return ratings

def read_tags(filename):
    """Прочитать теги из CSV"""
    tags = []
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                tag_id = row['userId'] + '_' + row['movieId'] + '_' + row['tag']
                user_id = row['userId']
                movie_id = row['movieId']
                tag = row['tag']
                timestamp = row['timestamp']
                tags.append((tag_id, user_id, movie_id, tag, timestamp))
    except Exception as e:
        print(f"Error reading {filename}: {e}")
    return tags

def read_users(filename):
    """Прочитать информацию о пользователях"""
    users = []
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    parts = line.split('|')
                    if len(parts) >= 5:
                        user_id = parts[0]
                        name = parts[1] if len(parts) > 1 else ''
                        email = parts[2] if len(parts) > 2 else ''
                        gender = parts[3] if len(parts) > 3 else ''
                        register_date = parts[4] if len(parts) > 4 else ''
                        occupation = parts[5] if len(parts) > 5 else ''
                        users.append((user_id, name, email, gender, register_date, occupation))
                except Exception as e:
                    print(f"Error parsing line {line_num} in {filename}: {e}")
    except Exception as e:
        print(f"Error reading {filename}: {e}")
    return users

def generate_sql_script(output_filename='db_init.sql'):
    """Генерировать SQL скрипт для создания БД и загрузки данных"""
    
    script_lines = []
    
    # Начало скрипта
    script_lines.append('-- Generated by make_db_init.py at ' + datetime.now().isoformat())
    script_lines.append('')
    
    # Удаление существующих таблиц
    script_lines.append('DROP TABLE IF EXISTS ratings;')
    script_lines.append('DROP TABLE IF EXISTS tags;')
    script_lines.append('DROP TABLE IF EXISTS movies;')
    script_lines.append('DROP TABLE IF EXISTS users;')
    script_lines.append('')
    
    # Создание таблицы movies
    script_lines.append('CREATE TABLE movies (')
    script_lines.append('    id INTEGER PRIMARY KEY,')
    script_lines.append('    title TEXT NOT NULL,')
    script_lines.append('    year INTEGER,')
    script_lines.append('    genres TEXT')
    script_lines.append(');')
    script_lines.append('')
    
    # Создание таблицы users
    script_lines.append('CREATE TABLE users (')
    script_lines.append('    id INTEGER PRIMARY KEY,')
    script_lines.append('    name TEXT,')
    script_lines.append('    email TEXT,')
    script_lines.append('    gender TEXT,')
    script_lines.append('    register_date TEXT,')
    script_lines.append('    occupation TEXT')
    script_lines.append(');')
    script_lines.append('')
    
    # Создание таблицы ratings
    script_lines.append('CREATE TABLE ratings (')
    script_lines.append('    id INTEGER PRIMARY KEY,')
    script_lines.append('    user_id INTEGER,')
    script_lines.append('    movie_id INTEGER,')
    script_lines.append('    rating REAL,')
    script_lines.append('    timestamp INTEGER')
    script_lines.append(');')
    script_lines.append('')
    
    # Создание таблицы tags
    script_lines.append('CREATE TABLE tags (')
    script_lines.append('    id INTEGER PRIMARY KEY,')
    script_lines.append('    user_id INTEGER,')
    script_lines.append('    movie_id INTEGER,')
    script_lines.append('    tag TEXT,')
    script_lines.append('    timestamp INTEGER')
    script_lines.append(');')
    script_lines.append('')
    
    # Чтение и вставка данных из файлов
    print("Reading data files...")
    
    # Загрузка фильмов
    print("Loading movies...")
    movies = read_movies('movies.csv')
    for movie_id, title, year, genres in movies:
        title_escaped = title.replace("'", "''")
        genres_escaped = genres.replace("'", "''")
        year_val = f"{year}" if year else "NULL"
        script_lines.append(f"INSERT INTO movies (id, title, year, genres) VALUES ({movie_id}, '{title_escaped}', {year_val}, '{genres_escaped}');")
    
    script_lines.append('')
    
    # Загрузка пользователей
    print("Loading users...")
    users = read_users('users.txt')
    for user_id, name, email, gender, register_date, occupation in users:
        name_escaped = name.replace("'", "''")
        email_escaped = email.replace("'", "''")
        occupation_escaped = occupation.replace("'", "''")
        script_lines.append(f"INSERT INTO users (id, name, email, gender, register_date, occupation) VALUES ({user_id}, '{name_escaped}', '{email_escaped}', '{gender}', '{register_date}', '{occupation_escaped}');")
    
    script_lines.append('')
    
    # Загрузка рейтингов
    print("Loading ratings...")
    ratings = read_ratings('ratings.csv')
    for idx, (rating_id, user_id, movie_id, rating, timestamp) in enumerate(ratings, 1):
        script_lines.append(f"INSERT INTO ratings (id, user_id, movie_id, rating, timestamp) VALUES ({idx}, {user_id}, {movie_id}, {rating}, {timestamp});")
    
    script_lines.append('')
    
    # Загрузка тегов
    print("Loading tags...")
    tags = read_tags('tags.csv')
    for idx, (tag_id, user_id, movie_id, tag, timestamp) in enumerate(tags, 1):
        tag_escaped = tag.replace("'", "''")
        script_lines.append(f"INSERT INTO tags (id, user_id, movie_id, tag, timestamp) VALUES ({idx}, {user_id}, {movie_id}, '{tag_escaped}', {timestamp});")
    
    script_lines.append('')
    
    # Запись в файл
    print(f"Writing SQL script to {output_filename}...")
    try:
        with open(output_filename, 'w', encoding='utf-8') as f:
            f.write('\n'.join(script_lines))
        print(f"Successfully generated {output_filename}")
    except Exception as e:
        print(f"Error writing to {output_filename}: {e}")

if __name__ == '__main__':
    generate_sql_script('db_init.sql')
